In [1]:
# Google Colab Notebook: Merge Two Data Files Using Pandas

# Import necessary libraries
import pandas as pd

# Create two sample dataframes (simulating data files)
data1 = {'ID': [1, 2, 3, 4], 'Name': ['Alice', 'Bob', 'Charlie', 'David'], 'Score': [85, 90, 88, 76]}
data2 = {'ID': [3, 4, 5, 6], 'Name': ['Charlie', 'David', 'Eve', 'Frank'], 'Grade': ['B', 'C', 'A', 'B']}

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

# Display the original dataframes
print("DataFrame 1:")
print(df1)
print("\nDataFrame 2:")
print(df2)

# Perform different types of merges using Name column only
inner_merge = pd.merge(df1, df2, on='Name', how='inner')
left_merge = pd.merge(df1, df2, on='Name', how='left')
right_merge = pd.merge(df1, df2, on='Name', how='right')
outer_merge = pd.merge(df1, df2, on='Name', how='outer')

# Display results
print("\nInner Merge (Only matching rows):")
print(inner_merge)

print("\nLeft Merge (All from df1, matching from df2):")
print(left_merge)

print("\nRight Merge (All from df2, matching from df1):")
print(right_merge)

print("\nOuter Merge (All data, merging where possible):")
print(outer_merge)

DataFrame 1:
   ID     Name  Score
0   1    Alice     85
1   2      Bob     90
2   3  Charlie     88
3   4    David     76

DataFrame 2:
   ID     Name Grade
0   3  Charlie     B
1   4    David     C
2   5      Eve     A
3   6    Frank     B

Inner Merge (Only matching rows):
   ID_x     Name  Score  ID_y Grade
0     3  Charlie     88     3     B
1     4    David     76     4     C

Left Merge (All from df1, matching from df2):
   ID_x     Name  Score  ID_y Grade
0     1    Alice     85   NaN   NaN
1     2      Bob     90   NaN   NaN
2     3  Charlie     88   3.0     B
3     4    David     76   4.0     C

Right Merge (All from df2, matching from df1):
   ID_x     Name  Score  ID_y Grade
0   3.0  Charlie   88.0     3     B
1   4.0    David   76.0     4     C
2   NaN      Eve    NaN     5     A
3   NaN    Frank    NaN     6     B

Outer Merge (All data, merging where possible):
   ID_x     Name  Score  ID_y Grade
0   1.0    Alice   85.0   NaN   NaN
1   2.0      Bob   90.0   NaN   NaN
2   3.0  Charlie   88.0   3.0     B
3   4.0    David   76.0   4.0     C
4   NaN      Eve    NaN   5.0     A
5   NaN    Frank    NaN   6.0     B